var marquees = [272, 273, 293, 467, 520, 552, 721, 749, 831, 890, 906, 922];
var upcomings = [334, 574, 712, 1051];
var total = [81, 202, 233, 283, 334, 435, 574, 712, 863, 991, 992, 1016, 1051, 1156, 1180, 1227, 1234, 1235, 1287, 1301];

var festivals = [
  {
	id:272,
	fname:"Sundance Film Festival",
    description:"From its earliest, pre-Robert Redford days as the U.S. Film Festival, this frosty January event in Utah's ski resort hamlet Park City has championed independence in American moviemaking and was key to the emergence of American Independent cinema from the early 1980s onward. Despite its high media profile these days, Sundance maintains sections devoted to non-commercial or \"experimental\" work and each year premieres some of the finest documentaries around.",
    film_count:222,
    start_date:null,
    end_date:null,
    url_fname:"sundance_film_festival"},
  {
	id:273,
	fname:"South by Southwest Film Festival",
    description:"Though perhaps best known for its music and barbecue, the annual multi-media mega-event SXSW has seen its simultaneous film festival steadily gain stature. It is a filmmaker-friendly showcase emphasizing new talent, networking, midnite-type movies and a relaxed atmosphere despite increasing Hollywood presence.",
    film_count:110,
    start_date:null,
    end_date:null,
    url_fname:"south_by_southwest_film_festival"},
  {id:293,
    fname:"Thessaloniki Film Festival",
    description:"Founded in 1960 to showcase emerging Greek cinema, Thessaloniki has in more recent years maintained that mission while expanding to accommodate movies from around the world (with special emphasis on new directors, independent filmmaking and work from the entire Balkans region).",
    film_count:193,
    start_date:null,
    end_date:null,
    url_fname:"thessaloniki_film_festival"},
  {id:467,
    fname:"Venice International Film Festival",
    description:"The granddaddy of all film festivals, Venice was founded in 1932 and has (excepting a few years during World War II) run annually ever since. It retains a grey eminence unshaken by many changes over the years, the prestige of its competitive selections and awards undiminished by the rise of myriad upstart rivals.",
    film_count:132,
    start_date:null,
    end_date:null,
    url_fname:"venice_international_film_festival"},
  {id:520,
    fname:"Cannes Film Festival",
    description:"For sheer glamour there's never been a festival to rival Cannes, whose French Riviera location and fabled lavish parties have magnetized jet-setters and paparazzi alike since 1946. But beyond the klieg-light glare there has always been serious attention paid to the art of cinema (with an award from Cannes carrying major global prestige).",
    film_count:262,
    start_date:null,
    end_date:null,
    url_fname:"cannes_film_festival"},
  {id:552,
    fname:"Karlovy Vary International Film Festival",
    description:"The leading film festival in Eastern Europe, Karlovy Vary started just after World War II and saw the flowering (and governmental shutdown) of the fabled 1960s Czech New Wave. The festival then survived major internal problems after the demise of Czechoslovakia itself. Now it has stabilized once again into an important showcase for cinema both regional and from around the world.",
    film_count:212,
    start_date:null,
    end_date:null,
    url_fname:"karlovy_vary_international_film_festival"},
  {id:721,
    fname:"Tribeca Film Festival",
    description:"A relative latecomer to the film festival scene, Tribeca was launched by Robert De Niro and partners in the wake of September 11, 2001, to promote NYC's general recovery and enduring vigor as a filmmaking center. It immediately shot to the upper ranks of global festival awareness thanks to its mix of independent, international and Hollywood work, with plenty of annual star power cinching the deal.",
    film_count:80,
    start_date:null,
    end_date:null,
    url_fname:"tribeca_film_festival"},
  {id:749,
    fname:"International Film Festival Rotterdam",
    description:"Though not as historied as some of its equals on the European festival scene, Rotterdam has become as influential in many respects as the more fabled Cannes, Venice and Berlin festivals. Its emphasis on new artistic currents has, among other things, made it a notable spotlight for emerging Asian filmmakers.",
    film_count:205,
    start_date:null,
    end_date:null,
    url_fname:"international_film_festival_rotterdam"},
  {id:831,
    fname:"Berlinale",
    description:"Edgier and less star-driven than some of its (few) equals on the international festival scene, this wintertime event has highlighted artistically adventuresome work from around the globe since 1951. It also boasts a market component that has launched numerous high-profile talents outside the official festival program.",
    film_count:328,
    start_date:null,
    end_date:null,
    url_fname:"berlinale"},
  {id:890,
    fname:"Telluride Film Festival",
    description:"Founded in 1974 by Bill and Stella Pence, James Card and Tom Luddy , Telluride remains unique among high-profile festivals: it grants no awards, utilizes a different guest program director each year (they’ve ranged from literary lions to film and theater titans) and features world and North American premieres. It's a long-weekend cinephile blitz with a rarefied atmosphere beloved by filmmakers and fans alike.",
    film_count:27,
    start_date:null,
    end_date:null,
    url_fname:"telluride_film_festival"},
  {id:906,
    fname:"Toronto International Film Festival",
    description:"Something of an upstart among the highest-profile festivals worldwide (though it's been around since 1976), TIFF now has no rival but Sundance and Telluride among North American festivals as both a talent launching pad and focus of media attention. Its position in early fall also means it is considered the preeminent springboard for movies destined for that year's Top Ten lists and Oscar campaigns.",
    film_count:343,
    start_date:null,
    end_date:null,
    url_fname:"toronto_international_film_festival"},
  {id:922,
    fname:"International Documentary Film Festival Amsterdam",
    description:"Since 1983 this expansive Dutch forum for non-fiction filmmaking has thrown a spotlight on documentaries of various lengths and nationalities, with prestigious prizes awarded in several categories.",
    film_count:48,
    start_date:null,
    end_date:null,
    url_fname:"international_documentary_film_festival_amsterdam"},
  {id:202,
    fname:"Bend Film Festival",
    description:"Surrounded by the spectacular scenery of Central Oregon, this\r\nOctober festival offers a “celebration of independent cinema”\r\nin its myriad forms around the world, from documentary to drama to animation. It also runs educational programs throughout the region, and supports young talent though its “BendFilm Future Filmmakers” program.",
    film_count:9,
    start_date:null,
    end_date:null,
    url_fname:"bend_film_festival"},
  {id:992,
    fname:"Camden International Film Festival",
    description:"Since 2005, this coastal Maine event has showcased the best in non-fiction filmmaking each September. Beyond screenings, its activities include panels, workshops, exhibits, concerts and the Points North Documentary Forum, a two-day conference offering networking and education opportunities between filmmakers and industry veterans.",
    film_count:16,
    start_date:null,
    end_date:null,
    url_fname:"camden_international_film_festival"},
  {id:81,
    fname:"Hot Springs Documentary Film Festival",
    description:"North America’s oldest festival dedicated exclusively to non-fiction cinema, HSDFF has (since 1992) presented the best in international documentaries along with panels, forums and other special events. Patrons overdosing on cinematic reality will find temporary escape easy as pie as the festival is adjacent not only to Hot Springs National Park but to this historic Arkansas destination town’s “Bathhouse Row” of preserved original spa facilities.",
    film_count:8,
    start_date:null,
    end_date:null,
    url_fname:"hot_springs_documentary_film_festival"},
  {id:233,
    fname:"San Francisco Jewish Film Festival",
    description:"Founded in 1980 as the first entirely Jewish-themed film festival, SFJFF remains the world's largest. Its principal annual event opens with a late-July week at San Francisco's historic Castro Theatre and then moves to consecutive runs in the East Bay, down the Peninsula and north to Marin. Amidst archival and new films reflecting the international Jewish experience, the festival has been unafraid to provoke community debate by programming diverse (and sometimes controversial) takes on Middle Eastern politics.",
    film_count:15,
    start_date:null,
    end_date:null,
    url_fname:"san_francisco_jewish_film_festival"},
  {id:283,
    fname:"New Orleans Film Festival",
    description:"As if anyone needed additional reasons to visit New Orleans, this October festival combines the city's signature penchants for food, drink, music and parties with eight days of international cinema, industry panels, starry guests and more. Founded in 1989, it lost a year to Hurricane Katrina but has since entered a period of rapid growth.",
    film_count:23,
    start_date:null,
    end_date:null,
    url_fname:"new_orleans_film_festival"},
  {id:334,
    fname:"Full Frame Documentary Film Festival",
    description:"Durham, North Carolina, is home to this annual prize-awarding showcase for non-fiction cinema. Since its birth in 1998, the springtime festival has featured special tributes to world-class filmmakers and a themed series curated by one or more illustrious guests (in addition to the latest and greatest in international documentary work).",
    film_count:19,
    start_date:"2015-04-09",
    end_date:"2015-04-12",
    url_fname:"full_frame_documentary_film_festival"},
  {id:435,
    fname:"Indie Memphis Film Festival",
    description:"American independent filmmaking in all its shapes and sizes is the focus for this annual fall event. In keeping with its fabled city setting, Indie Memphis also places considerable emphasis on live music and musician guests. The festival organization also provides special programming events year-round.",
    film_count:25,
    start_date:null,
    end_date:null,
    url_fname:"indie_memphis_film_festival"},
  {id:574,
    fname:"Miami International Film Festival",
    description:"Since 1984, MIFF has provided one of America's destination cities with an annual smorgasbord of global cinema. Venues across the city center host a wide-ranging program for ten days each March (with one reliable facet being an emphasis on the latest in Latin American filmmaking).",
    film_count:74,
    start_date:"2015-03-06",
    end_date:"2015-03-15",
    url_fname:"miami_international_film_festival"},
  {id:712,
    fname:"Independent Film Festival Boston",
    description:"Focusing on independent productions \"both innovative and crowd-pleasing... that people might not get a chance to see anywhere else,\" this relative newcomer has quickly made a place for itself in Boston's cultural landscape since its 2003 founding.",
    film_count:40,
    start_date:"2015-04-22",
    end_date:"2015-04-29",
    url_fname:"independent_film_festival_of_boston"},
  {id:863,
    fname:"Urbanworld Film Festival",
    description:"Preeminent annual multicultural showcase Urbanworld presents new work by minority filmmakers and about minority issues each fall in New York City with a particular emphasis on African-American, Latino and LGBTQ cinema. It also offers panels, workshops, musical performances and live screenplay readings featuring celebrity guests.",
    film_count:6,
    start_date:null,
    end_date:null,
    url_fname:"urbanworld_film_festival"},
  {id:991,
    fname:"San Francisco Silent Film Festival",
    description:"The largest such event in the U.S., SFSFF has showcased films from the pre-\"talkie\" era since 1996, aptly presenting them (complete with live musical accompaniment) at the Castro Theatre, a preserved 1922 art deco movie palace. For several days each July, SFSFF shows silent films not just from Hollywood but around the world (along with a day-long event each winter and occasional silent programs at other times throughout the year).",
    film_count:34,
    start_date:null,
    end_date:null,
    url_fname:"san_francisco_silent_film_festival"},
  {id:1016,
    fname:"Global Peace Film Festival",
    description:"Though Florida may generally run toward the \"red\" side of the political spectrum, you will find plenty of progressivism on- and off-screen at this mid-September Orlando event. Its mix of documentary and narrative works throw a spotlight on environmental, human rights and innumerable other issues around the world (with an emphasis on encouraging audience activism).",
    film_count:10,
    start_date:null,
    end_date:null,
    url_fname:"global_peace_film_festival"},
  {id:1051,
    fname:"Ashland Independent Film Festival",
    description:"You can brush up on your Shakespeare most of the year in this pretty Oregon college town. But for five days each April the main cultural event in Ashland is not its famed theater festival but AIFF. The film festival showcases the independent spirit in narrative and documentary filmmaking from around the world.",
    film_count:16,
    start_date:"2015-04-09",
    end_date:"2015-04-13",
    url_fname:"ashland_independent_film_festival"},
  {id:1156,
    fname:"Napa Valley Film Festival",
    description:"Billed as \"the ultimate film, food and wine experience,\" this five-day November festival taking place across Northern California's celebrated wine region gives visitors a taste (or three) from the area's best restaurants and vineyards. Plus, of course, a generous sampling of the latest in international cinema, including a competitive Artist in Residence program for narrative and documentary makers along with red-carpet events and more.",
    film_count:11,
    start_date:null,
    end_date:null,
    url_fname:"napa_valley_film_festival"},
  {id:1180,
    fname:"Lone Star Film Festival",
    description:"Held early each November in Fort Worth's Sundance Square, this fast-growing event offers a healthy mix of new work from both acclaimed and emerging talent from around the globe. While newcomers can compete for Narrative and Documentary Feature prizes, the festival has also showcased established luminaries, including the Texas-born-and-raised likes of Billy Bob Thornton, Lyle Lovett and Robert Rodriguez.",
    film_count:34,
    start_date:null,
    end_date:null,
    url_fname:"lone_star_film_festival"},
  {id:1227,
    fname:"Nantucket Film Festival",
    description:"The picturesque New England coastal hamlet's annual late-June festival (founded by Jill Burkhart and her brother Jonathan) features a mix of narrative and documentary work from the U.S. and beyond. Recurring highlights include an all-star comedy roundtable, the equally glittery live \"Late Night Storytelling\" programs plus a major emphasis on showcasing and supporting the art of screenwriting.",
    film_count:19,
    start_date:null,
    end_date:null,
    url_fname:"nantucket_film_festival"},
  {id:1234,
    fname:"Oak Cliff Film Festival",
    description:"A relatively recent addition to the film festival world, this June event in one of Dallas' oldest districts pays special attention to work from Texas filmmakers while also providing a diverse sampler of recent world cinema highlights.",
    film_count:11,
    start_date:null,
    end_date:null,
    url_fname:"oak_cliff_film_festival"},
  {id:1235,
    fname:"Santa Fe Independent Film Festival",
    description:"New Mexico's picturesque capital is the setting for this late fall festival, fnamed by MovieMaker as one of \"coolest film festivals on the planet.\" In addition to the best of recent international cinema, there is an emphasis on American independent filmmaking, particularly from Native- and Latin-American makers.",
    film_count:6,
    start_date:null,
    end_date:null,
    url_fname:"sante_fe_independent_film_festival"},
  {id:1287,
    fname:"Houston Cinema Arts Festival",
    description:"HCAF’s annual five-day November event has a unique focus: its diverse programming all revolves around artistic creation itself, with the emphasis on work that \"celebrates the visual, performing and literary arts.\" In addition to both narrative and documentary films about artists, the festival features video installations, live multimedia shows and more, often presented in conjunction with other leading Houston cultural institutions.",
    film_count:26,
    start_date:null,
    end_date:null,
    url_fname:"houston_cinema_arts_festival"},
  {id:1301,
    fname:"First Look",
    description:"This recent arrival on the U.S. festival scene is an annual program of New York City’s famed Museum of the Moving Image. The January event provides a curated selection of the best in new international features and shorts.",
    film_count:3,
    start_date:null,
    end_date:null,
    url_fname:"first_look"}];